name: webdriverio-en-us

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '10 4 * * *'

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Lint with eslint
      run: npm run lint
    - name: Test with wdio
      run: npm run test
